### ISSUE TITLE
Editor page is not loading

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon.js#110]
Trace code and find a way to get the editor window to load.

**Comment by ATranimal** [comment]
Initial issue was due to the importing the JS files, and the paths were incorrect because we organized them into MVC folders. We now have a second bug of not being able to find the image and mei files, need to figure out the pathing. 
`WARNING:tornado.access:404 GET /MEI_DIRECTORY/squarenote/0371_corr.mei (::1) 32.76ms
WARNING:tornado.access:404 GET /MEI_DIRECTORY/squarenote/0371_corr.jpg (::1) 1.18ms`

**Comment by zoemcl** [comment]
Issue fixed. Images were in .png format and should have been in .jpeg.
