### ISSUE TITLE
Resizing

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon.js#116]
there are no resizing options available either for the image or for the notes.

**Comment by ATranimal** [comment]
This is important because some MEI files that we upload are not scaled correctly and render all on the sides/don't fit the canvas. 
![screen shot 2017-05-16 at 12 13 18 pm](https://cloud.githubusercontent.com/assets/13473087/26116476/48e0538e-3a31-11e7-9443-7b549d227a96.png)

**Comment by ATranimal** [comment]
Started work on this in 53c480db8289601bf1257a3b89c8e3917523931b

There remains an issue of how to get the resizing/scaling to work dynamically, as right now, the scaling only affects elements that are placed after the slider has been changed. Need to find a way to re-render the entire canvas / objects after a change, as a possible solution. Trying to loop through all the objects and change their values individually ended up just growing them and shrinking them in place. There must be a way to do it because changing the page.scale manually in the Neon initiation stage give intended results, but have yet to get it to work dynamically.

Also unsure about whether to use global scale vs page scale, need to do some more research on that. globalScale is a fabric.js variable, while page scale is part of the Neon structure.

**Comment by ATranimal** [comment]
No longer updating fabric.js
