### ISSUE TITLE
No way to exit Info or Alert

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon.js#136]
As stated above, when Neon generates an alert or provides information for a selected element, there is an "X" but when clicked it does not do anything.

**Comment by ATranimal** [comment]
Here what we're thinking:
Seems like it'll be hard to implement the closing of the alert in the bootstrap way because we're not even sure what version of bootstrap we're on and changes to the html don't seem to be doing anything.

A possible workaround is to use the functions in interaction.js like hideInfo and hideAlert to simply set the alert/info boxes to be 0% opaque, and write up a handler, binder, and function in squarenoteinteraction to close the alerts.

**Comment by ATranimal** [comment]
Started in 74ee67b6b40e69364ea9423ff961dca7d7064879

**Comment by ATranimal** [comment]
Completed in 32b6d1228f2138d2c2fa01a53f9b41ef8c36706e

The issue was that there were conflicts between the default bootstrap closing alert behaviour and our neon.js jquery code for closing.
